@startuml
skinparam shadowing false
hide members
hide circle
class "H.Diagnosis1"
class "H.Bed1"
class "H.OP1"
class "H.Receiption"
class "H.Emergency"
class "H'.Bed2"
class "H'.OP2"
class "H'.Bed1"
class "H'.OP1"
class "H'.Receiption"
class "H'.Emergency"
class "H''.Diagnosis2"
class "H''.Bed2"
class "H''.OP2"
class "H''.Bed1"
class "H''.OP1"
class "H''.Emergency"
class "Ĥ.Bed1"
class "Ĥ.OP1"
class "Ĥ.Receiption"
class "Ĥ.Emergency"
class "Ĥ'.Bed2"
class "Ĥ'.OP2"
class "Ĥ'.Bed1"
class "Ĥ'.OP1"
class "Ĥ'.Emergency"
class "H#.Bed1"
class "H#.OP1"
class "H#.Emergency"

"H#.Bed1" --> "Ĥ.Bed1" : "H#δ-"
"H#.OP1" --> "Ĥ.OP1" : "H#δ-"
"H#.Emergency" --> "Ĥ.Emergency" : "H#δ-"
"H#.Bed1" --> "Ĥ'.Bed1" : "H#δ+"
"H#.OP1" --> "Ĥ'.OP1" : "H#δ+"
"H#.Emergency" --> "Ĥ'.Emergency" : "H#δ+"
"Ĥ.Bed1" --> "H.Bed1" : "Ĥδ-"
"Ĥ.OP1" --> "H.OP1" : "Ĥδ-"
"Ĥ.Receiption" --> "H.Receiption" : "Ĥδ-"
"Ĥ.Emergency" --> "H.Emergency" : "Ĥδ-"
"Ĥ.Bed1" --> "H'.Bed1" : "Ĥδ+"
"Ĥ.OP1" --> "H'.OP1" : "Ĥδ+"
"Ĥ.Receiption" --> "H'.Receiption" : "Ĥδ+"
"Ĥ.Emergency" --> "H'.Emergency" : "Ĥδ+"
"Ĥ'.Bed2" --> "H'.Bed2" : "Ĥ'δ-"
"Ĥ'.OP2" --> "H'.OP2" : "Ĥ'δ-"
"Ĥ'.Bed1" --> "H'.Bed1" : "Ĥ'δ-"
"Ĥ'.OP1" --> "H'.OP1" : "Ĥ'δ-"
"Ĥ'.Emergency" --> "H'.Emergency" : "Ĥ'δ-"
"Ĥ'.Bed2" --> "H''.Bed2" : "Ĥ'δ+"
"Ĥ'.OP2" --> "H''.OP2" : "Ĥ'δ+"
"Ĥ'.Bed1" --> "H''.Bed1" : "Ĥ'δ+"
"Ĥ'.OP1" --> "H''.OP1" : "Ĥ'δ+"
"Ĥ'.Emergency" --> "H''.Emergency" : "Ĥ'δ+"
"H#.Bed1" --> "H.Bed1" : "(H#δ-;Ĥδ-)"
"H#.OP1" --> "H.OP1" : "(H#δ-;Ĥδ-)"
"H#.Emergency" --> "H.Emergency" : "(H#δ-;Ĥδ-)"
"H#.Bed1" --> "H''.Bed1" : "(H#δ+;Ĥ'δ+)"
"H#.OP1" --> "H''.OP1" : "(H#δ+;Ĥ'δ+)"
"H#.Emergency" --> "H''.Emergency" : "(H#δ+;Ĥ'δ+)"
@enduml
