@startuml
digraph Diagram {
  "H";
  "H'";
  "H''";
  "Ĥ";
  "Ĥ'";
  "H#";
  "H#"->"Ĥ" [label=" H#δ₋"];
  "H#"->"Ĥ'" [label=" H#δ₊"];
  "Ĥ"->"H" [label=" Ĥδ₋"];
  "Ĥ"->"H'" [label=" Ĥδ₊"];
  "Ĥ'"->"H'" [label=" Ĥ'δ₋"];
  "Ĥ'"->"H''" [label=" Ĥ'δ₊"];
  "H#"->"H" [label=" (H#δ₋;Ĥδ₋)"];
  "H#"->"H''" [label=" (H#δ₊;Ĥ'δ₊)"];
}
@enduml
