@startuml
skinparam shadowing false
hide members
hide circle
class "H.Diagnosis1"
class "H.Bed1"
class "H.OP1"
class "H.Receiption"
class "H.Emergency"
class "H'.Bed2"
class "H'.OP2"
class "H'.Bed1"
class "H'.OP1"
class "H'.Receiption"
class "H'.Emergency"
class "H''.Diagnosis2"
class "H''.Bed2"
class "H''.OP2"
class "H''.Bed1"
class "H''.OP1"
class "H''.Emergency"
class "G.Bed1"
class "G.OP1"
class "G.Receiption"
class "G.Emergency"
class "R.Bed2"
class "R.OP2"
class "R.Bed1"
class "R.OP1"
class "R.Emergency"
class "Ħ.Bed1"
class "Ħ.OP1"
class "Ħ.Emergency"

"Ħ.Bed1" --> "G.Bed1" : "Ħδ-"
"Ħ.OP1" --> "G.OP1" : "Ħδ-"
"Ħ.Emergency" --> "G.Emergency" : "Ħδ-"
"Ħ.Bed1" --> "R.Bed1" : "Ħδ+"
"Ħ.OP1" --> "R.OP1" : "Ħδ+"
"Ħ.Emergency" --> "R.Emergency" : "Ħδ+"
"G.Bed1" --> "H.Bed1" : "Gδ-"
"G.OP1" --> "H.OP1" : "Gδ-"
"G.Receiption" --> "H.Receiption" : "Gδ-"
"G.Emergency" --> "H.Emergency" : "Gδ-"
"G.Bed1" --> "H'.Bed1" : "Gδ+"
"G.OP1" --> "H'.OP1" : "Gδ+"
"G.Receiption" --> "H'.Receiption" : "Gδ+"
"G.Emergency" --> "H'.Emergency" : "Gδ+"
"R.Bed2" --> "H'.Bed2" : "Rδ-"
"R.OP2" --> "H'.OP2" : "Rδ-"
"R.Bed1" --> "H'.Bed1" : "Rδ-"
"R.OP1" --> "H'.OP1" : "Rδ-"
"R.Emergency" --> "H'.Emergency" : "Rδ-"
"R.Bed2" --> "H''.Bed2" : "Rδ+"
"R.OP2" --> "H''.OP2" : "Rδ+"
"R.Bed1" --> "H''.Bed1" : "Rδ+"
"R.OP1" --> "H''.OP1" : "Rδ+"
"R.Emergency" --> "H''.Emergency" : "Rδ+"
"Ħ.Bed1" --> "H.Bed1" : "(Ħδ-;Gδ-)"
"Ħ.OP1" --> "H.OP1" : "(Ħδ-;Gδ-)"
"Ħ.Emergency" --> "H.Emergency" : "(Ħδ-;Gδ-)"
"Ħ.Bed1" --> "H''.Bed1" : "(Ħδ+;Rδ+)"
"Ħ.OP1" --> "H''.OP1" : "(Ħδ+;Rδ+)"
"Ħ.Emergency" --> "H''.Emergency" : "(Ħδ+;Rδ+)"
@enduml
