@startuml
skinparam shadowing false
hide members
hide circle
class "H.doctor1"
class "H.doctor2"
class "H.nurse1"
class "H.nurse2"
class "H.secretarian"
class "H'.doctor1"
class "H'.nurse1"
class "H'.nurse2"
class "H'.nurse3"
class "H'.nurse4"
class "H'.secretarian"
class "H''.doctor1"
class "H''.nurse1"
class "H''.nurse2"
class "H''.nurse3"
class "H''.nurse4"
class "H''.nurse5"
class "Ĥ.doctor1"
class "Ĥ.nurse1"
class "Ĥ.nurse2"
class "Ĥ.secretarian"
class "Ĥ'.doctor1"
class "Ĥ'.nurse1"
class "Ĥ'.nurse2"
class "Ĥ'.nurse3"
class "Ĥ'.nurse4"
class "H#.doctor1"
class "H#.nurse1"
class "H#.nurse2"

"H#.doctor1" --> "Ĥ.doctor1" : "H#δ₋"
"H#.nurse1" --> "Ĥ.nurse1" : "H#δ₋"
"H#.nurse2" --> "Ĥ.nurse2" : "H#δ₋"
"H#.doctor1" --> "Ĥ'.doctor1" : "H#δ₊"
"H#.nurse1" --> "Ĥ'.nurse1" : "H#δ₊"
"H#.nurse2" --> "Ĥ'.nurse2" : "H#δ₊"
"Ĥ.doctor1" --> "H.doctor1" : "Ĥδ₋"
"Ĥ.nurse1" --> "H.nurse1" : "Ĥδ₋"
"Ĥ.nurse2" --> "H.nurse2" : "Ĥδ₋"
"Ĥ.secretarian" --> "H.secretarian" : "Ĥδ₋"
"Ĥ.doctor1" --> "H'.doctor1" : "Ĥδ₊"
"Ĥ.nurse1" --> "H'.nurse1" : "Ĥδ₊"
"Ĥ.nurse2" --> "H'.nurse2" : "Ĥδ₊"
"Ĥ.secretarian" --> "H'.secretarian" : "Ĥδ₊"
"Ĥ'.doctor1" --> "H'.doctor1" : "Ĥ'δ₋"
"Ĥ'.nurse1" --> "H'.nurse1" : "Ĥ'δ₋"
"Ĥ'.nurse2" --> "H'.nurse2" : "Ĥ'δ₋"
"Ĥ'.nurse3" --> "H'.nurse3" : "Ĥ'δ₋"
"Ĥ'.nurse4" --> "H'.nurse4" : "Ĥ'δ₋"
"Ĥ'.doctor1" --> "H''.doctor1" : "Ĥ'δ₊"
"Ĥ'.nurse1" --> "H''.nurse1" : "Ĥ'δ₊"
"Ĥ'.nurse2" --> "H''.nurse2" : "Ĥ'δ₊"
"Ĥ'.nurse3" --> "H''.nurse3" : "Ĥ'δ₊"
"Ĥ'.nurse4" --> "H''.nurse4" : "Ĥ'δ₊"
"H#.doctor1" --> "H.doctor1" : "(H#δ₋;Ĥδ₋)"
"H#.nurse1" --> "H.nurse1" : "(H#δ₋;Ĥδ₋)"
"H#.nurse2" --> "H.nurse2" : "(H#δ₋;Ĥδ₋)"
"H#.doctor1" --> "H''.doctor1" : "(H#δ₊;Ĥ'δ₊)"
"H#.nurse1" --> "H''.nurse1" : "(H#δ₊;Ĥ'δ₊)"
"H#.nurse2" --> "H''.nurse2" : "(H#δ₊;Ĥ'δ₊)"
@enduml
