@startuml
digraph Diagram {
  "X";
  "Z";
  "empty";
  "(X_X_Z)"->"X" [label=" πX"];
  "(X_X_Z)"->"Z" [label=" πZ"];
  "empty"->"X" [label=" empty"];
  "empty"->"Z" [label=" empty"];
  "empty"->"(X_X_Z)" [label=" (empty->(X_X_Z))"];
  "empty"->"empty" [label=" id_empty"];
}
@enduml
