@startuml
skinparam shadowing false
hide members
hide circle
class "X.a"
class "X.b"
class "X.c"
class "Z.a"
class "Z.3"
class "Z.foo"

"(X_X_Z).a=a" --> "X.a" : "πX"
"(X_X_Z).a=3" --> "X.a" : "πX"
"(X_X_Z).a=foo" --> "X.a" : "πX"
"(X_X_Z).b=a" --> "X.b" : "πX"
"(X_X_Z).b=3" --> "X.b" : "πX"
"(X_X_Z).b=foo" --> "X.b" : "πX"
"(X_X_Z).c=a" --> "X.c" : "πX"
"(X_X_Z).c=3" --> "X.c" : "πX"
"(X_X_Z).c=foo" --> "X.c" : "πX"
"(X_X_Z).a=a" --> "Z.a" : "πZ"
"(X_X_Z).a=3" --> "Z.3" : "πZ"
"(X_X_Z).a=foo" --> "Z.foo" : "πZ"
"(X_X_Z).b=a" --> "Z.a" : "πZ"
"(X_X_Z).b=3" --> "Z.3" : "πZ"
"(X_X_Z).b=foo" --> "Z.foo" : "πZ"
"(X_X_Z).c=a" --> "Z.a" : "πZ"
"(X_X_Z).c=3" --> "Z.3" : "πZ"
"(X_X_Z).c=foo" --> "Z.foo" : "πZ"
@enduml
