@startuml
digraph Diagram {
  "G";
  "R";
  "candidate";
  "(G_X_R)"->"G" [label=" πG"];
  "(G_X_R)"->"R" [label=" πR"];
  "candidate"->"G" [label=" candidate_G"];
  "candidate"->"R" [label=" candidate_R"];
  "candidate"->"(G_X_R)" [label=" (candidate->(G_X_R))"];
  "candidate"->"candidate" [label=" id_candidate"];
}
@enduml
