@startuml
skinparam shadowing false
hide members
hide circle
class "G.a"
class "G.b"
class "R.3"
class "candidate.a=3"
class "candidate.b=3"

"cartesian product_G_R.a=3" --> "G.a" : "pi_G"
"cartesian product_G_R.b=3" --> "G.b" : "pi_G"
"cartesian product_G_R.a=3" --> "R.3" : "pi_R"
"cartesian product_G_R.b=3" --> "R.3" : "pi_R"
"candidate.a=3" --> "G.a" : "candidate_G"
"candidate.b=3" --> "G.b" : "candidate_G"
"candidate.a=3" --> "R.3" : "candidate_R"
"candidate.b=3" --> "R.3" : "candidate_R"
"cartesian product_G_R.a=3" --> "candidate.a=3" : "cartesian product_G_R_to_candidate"
"cartesian product_G_R.b=3" --> "candidate.b=3" : "cartesian product_G_R_to_candidate"
"candidate.a=3" --> "candidate.a=3" : "id_candidate"
"candidate.b=3" --> "candidate.b=3" : "id_candidate"
@enduml
