@startuml
digraph Diagram {
  "G";
  "R";
  "candidate";
  "cartesian product_G_R"->"G" [label=" pi_G"];
  "cartesian product_G_R"->"R" [label=" pi_R"];
  "candidate"->"G" [label=" candidate_G"];
  "candidate"->"R" [label=" candidate_R"];
  "cartesian product_G_R"->"candidate" [label=" cartesian product_G_R_to_candidate"];
  "candidate"->"candidate" [label=" id_candidate"];
}
@enduml
