@startuml
digraph Diagram {
  "X";
  "Z";
  "small";
  "(X_X_Z)"->"X" [label=" πX"];
  "(X_X_Z)"->"Z" [label=" πZ"];
  "small"->"X" [label=" small"];
  "small"->"Z" [label=" small"];
  "small"->"(X_X_Z)" [label=" (small->(X_X_Z))"];
  "small"->"small" [label=" id_small"];
}
@enduml
