@startuml
skinparam shadowing false
hide members
hide circle
class "B.P_B"
class "B.I_B"
class "A.X_A"
class "A.C_A"
class "A.D_A"
class "C.P_C"
class "C.A_C"
class "(πB;d'_eqFS_πC;b').P_B"
class "(C_X_B).P_C=P_B"
class "(C_X_B).P_C=I_B"
class "(C_X_B).A_C=P_B"
class "(C_X_B).A_C=I_B"

"B.P_B" --> "A.X_A" : "d'"
"B.I_B" --> "A.D_A" : "d'"
"C.P_C" --> "A.C_A" : "b'"
"C.A_C" --> "A.X_A" : "b'"
"(πB;d'_eqFS_πC;b').P_B" --> "B.P_B" : "((πB;d'_eqFS_πC;b')->(B_X_C));πB"
"(C_X_B).P_C=P_B" --> "C.P_C" : "πC"
"(C_X_B).P_C=I_B" --> "C.P_C" : "πC"
"(C_X_B).A_C=P_B" --> "C.A_C" : "πC"
"(C_X_B).A_C=I_B" --> "C.A_C" : "πC"
"(πB;d'_eqFS_πC;b').P_B" --> "C.A_C" : "((πB;d'_eqFS_πC;b')->(B_X_C));πC"
"(C_X_B).P_C=P_B" --> "B.P_B" : "πB"
"(C_X_B).P_C=I_B" --> "B.I_B" : "πB"
"(C_X_B).A_C=P_B" --> "B.P_B" : "πB"
"(C_X_B).A_C=I_B" --> "B.I_B" : "πB"
@enduml
