@startuml
digraph Diagram {
  "B";
  "A";
  "C";
  "(πB;d'_eqFS_πC;b')";
  "(C_X_B)";
  "B"->"A" [label=" d'"];
  "C"->"A" [label=" b'"];
  "(πB;d'_eqFS_πC;b')"->"B" [label=" ((πB;d'_eqFS_πC;b')->(B_X_C));πB"];
  "(C_X_B)"->"C" [label=" πC"];
  "(πB;d'_eqFS_πC;b')"->"C" [label=" ((πB;d'_eqFS_πC;b')->(B_X_C));πC"];
  "(C_X_B)"->"B" [label=" πB"];
}
@enduml
